linters:
  stylelint:
    config: 'stylelint.config.js'
files:
    ignore:
        - 'assets/css/reset.css'
        - 'assets/css/mediascreen.css'
        - 'assets/css/selector.css'
fixers:
    enable: true